spring:
  application:
    name: aggregator
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server

kafka:
  bootstrap-servers: localhost:9092
  value-serializer: ru.practicum.eventSerializer.AvroSerializer
  value-deserializer: ru.practicum.eventDeserializer.SensorEventDeserializer
  consumer:
    group-id: aggregator-group

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/