spring:
  application:
    name: shopping-store
  config:
    import: "optional:configserver:"
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 20
        initial-interval: 100
      discovery:
        enabled: true
        serviceId: config-server

#server:
#  port: 0
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/